### ISSUE TITLE
Workaround for files.upload API deprecation for newly-created Slack apps after May 16, 2024

### ISSUE THREAD

**Issue by akinobu-i** [yamitzky/redashbot#13]
https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay
> ### When does this happen?
>There are two keys dates to keep in mind:
>
> 1. As of May 16, 2024, newly-created Slack apps are no longer able to access the files.upload API. All new apps must use the new methods.
> 2. On March 11, 2025, the files.upload API will be sunset and no longer available. All apps, new and old, must use the new methods by this date.

Currently, newly created applications are failing to upload screenshots. According to the official documentation, it is recommended to use files.uploadV2 instead of files.upload.
I was able to resolve this issue by making the following change in handlers.ts:
```
- client.files.upload({
+ client.files.uploadV2({
```
This change allows the application to successfully upload screenshots using the updated files.uploadV2 API method, which is the recommended approach for newly created Slack apps after the deprecation of files.upload.
By sharing this workaround, I hope it helps others who may be facing similar issues with file uploads in their newly created Slack apps.

**Comment by yamitzky** [comment]
Fixed by https://github.com/yamitzky/redashbot/pull/14, thank you!
